#1.7.10传送至的服务器
Server1710: heartage3
#1.12.2传送至的服务器
Server1122A: heartage1
Server1122B: heartage2
Server1122C: heartage3
#1.13.2传送至的服务器
Server1132: heartage4
#默认子服
Servers: heartage0
#空子服
NullServer: null
#配置文件版本号
Version: 1.0.0